"""IR data structures."""

from aotc.ir.cfg import BasicBlock, FunctionIR, FunctionSignature, ModuleIR
from aotc.ir.node import (
    Alloca,
    BinOp,
    Branch,
    Call,
    Cast,
    Const,
    ExternDecl,
    GEP,
    GetField,
    Jump,
    Load,
    Phi,
    PtrCast,
    Return,
    Store,
    StructDef,
    StructField,
    Value,
)

__all__ = [
    "BasicBlock",
    "FunctionIR",
    "FunctionSignature",
    "ModuleIR",
    "Value",
    "Const",
    "BinOp",
    "Phi",
    "Alloca",
    "Load",
    "Store",
    "GEP",
    "GetField",
    "PtrCast",
    "Call",
    "Cast",
    "StructField",
    "StructDef",
    "ExternDecl",
    "Branch",
    "Jump",
    "Return",
]
